spring.application.name=Proyecto_TransSurExpress_JoseManuel_Diaz
server.port=8080
spring.datasource.url=jdbc:h2:mem:transsurdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true